### ISSUE TITLE
Different classes

### ISSUE THREAD

**Issue by Tony-WJR** [darrenjkt/MS3D#23]
Hi:

Thank you for your great work! Now my use case is, I want to autolabel a dataset we collected. But the classes I want to detect is ["car", "pedestrian", and "traffic cone"]. In waymo we mainly have [car, pedestrian, and cyclists], in nuscenes we have [car, pedestrian, bus, truck, traffic cone, ....]. 

Do you have some suggestions how should I use your method to do this? In my opinion, waymo do not have traffic cone class, so we cannot use it. nuScenes has all the classes I need, but how should I use the knowledge from nuScenes using your method? (Like I should train what network under what configuration?) Hope to hear from you soon. Thank you!

**Comment by darrenjkt** [comment]
You could train a nuscenes model (trained with SHIFT_COOR, 10 sweeps) on all the classes such you want such as car, pedestrian and traffic cone, then use that model alongside some waymo pretrained models to auto-label your dataset. 

Since traffic cones don't move, you use the nuscenes model to do inference point cloud sweeps of your own dataset. Thereafter, you can use our box fusion, KBF, to fuse box predictions of traffic cones across frames like we did for parked cars.

**Comment by Tony-WJR** [comment]
Hi Darren:

Thank you for your super fast reply, even in the weekend! :)

Our project actually focuses on the underground parking scenario, where cyclists do not often appear. So we only need to detect the car, pedestrian, and cones. You said we could train a nuscenes model on our target classes then combine with waymo pretrained model, that's a good idea. But waymo pretrained model includes the classes we do not want right? (like cyclists) How should I deal with that? Or you mean I train a model with only car and pedestrian on Waymo (mask the cyclist classes), then combine the model with the nuScenes model trained on the 3 target classes (mask the other classes)?

Thank you!

**Comment by darrenjkt** [comment]
You don't have to retrain the waymo model. They predictions have labels 0,1,2,3,etc. Just map the numbers to their respective class label and ignore the predictions for cyclist. 

Same with the nuscenes if you've already trained a model.

**Comment by Tony-WJR** [comment]
That makes sense. Thank you!
